language: node_js
node_js:
  - "stable"

cache:
  directories:
  - node_modules

install:
  - npm install
  - npm build

script:
  - npm test

after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
